### ISSUE TITLE
Error on submitting form, but email is received

### ISSUE THREAD

**Issue by rga10228** [mariovalney/cf7-to-zapier#10]
Hi there, 

I have your plugin on my WordPress website and have been using it for awhile with no issues. I noticed recently that when I submit a contact form, I get the following error after submitting it, however I am still receiving the email with no issue:

![image](https://user-images.githubusercontent.com/87872028/126815382-1bc83e0c-8e6e-4bf0-b352-c53a1468fbfc.png)

Troubleshooting steps:
1. I have tried downgrading the CF7 plugin multiple times all the way down to 5.2.1. 
2. I have ensured no caching plugins or browser caching is affecting things.
3. I have tested this on multiple browsers and in incognito mode. 
4. I know this is not a server issue, but just in case I have contacted my host to ensure the problem is not on their end, and double-checked all DNS settings. 
5. I have also set-up and re-configured SMTP (again, I know it's not a server issue, but I wanted to cover all of my bases).
6. I have disabled CAPTCHA.
7. Verified settings in the .htaccess file were correct.
8. I deactivated all other plugins to make sure the issue was not with anything else.
9. I downgraded the theme version that I am using and the error still persists there.
10. I checked Dev Console and the error I am seeing there is: "Failed to load resource: the server responded with a status of 404 ()"

Please help. Your plugin in VERY important for my business and I would like to continue using it. Thank you so much.

**Comment by mariovalney** [comment]
Hi. I guess, your item 10 is the answer:

> Failed to load resource: the server responded with a status of 404

Sounds like the webhook is not well configured.
Please, check it and/or try with a working webhook, like in https://webhook.site.

**Comment by rga10228** [comment]
Thank you so much, that looks like it was the issue!
