### ISSUE TITLE
Hidden Value 0 will be ignored in payload 

### ISSUE THREAD

**Issue by thorque** [mariovalney/cf7-to-zapier#13]
Hello,

I have a form with hidden fields. If the hidden field has a value other than 0 (zero) then this value is in payload. If the value is 0 then the filed exists in payload but it's empty. Can you check, if this is intended and what is a workaround for this?

Thanks
Thorsten

**Comment by mariovalney** [comment]
Hey! How are you?

I apologize for letting this issue slip by. During the holidays, I've been working on new features and revisited this issue. It will be fixed in the next version.
