### ISSUE TITLE
Activating webhook causes CF7 send error

### ISSUE THREAD

**Issue by cbeem1** [mariovalney/cf7-to-zapier#14]
When I activate my webhook on form submission, all data is sent to the webhook correctly, but CF7 says there is an error and will not redirect because it does not think the form was successfully submitted. Error message is: 
"There was an error trying to send your message. Please try again later."

**Comment by mariovalney** [comment]
Hi. How are you?

It seems a conflict with another plugin.

Please use the support forum:
https://wordpress.org/support/plugin/cf7-to-zapier/
