### ISSUE TITLE
Send email to webmaster if webhook fails

### ISSUE THREAD

**Issue by andersb** [mariovalney/cf7-to-zapier#15]
Must say I love this plugin. Super easy and customizable.

The one thing I'm missing is a simple way to be notified when a webhook request fails.

The plugin https://github.com/zaus/forms-3rdparty-integration does this, meaning, the webmaster gets an email with all information for the request and the error response from the webhook.

**Comment by mariovalney** [comment]
Thanks for your suggestion.
It'll be shipped with 4.0.0 version.
