### ISSUE TITLE
Support for remote IP address

### ISSUE THREAD

**Issue by ctschach** [mariovalney/cf7-to-zapier#16]
Hi love the simplicity of the Plugin. However, I miss one feature and that's getting the remote ip address for the person filling put the form.

While I've implemented now via the filter in the functions.php, it would be nice if this can be implemented natively.

**Comment by mariovalney** [comment]
Hey! How are you?
You may use a [Special Mail Tag](https://contactform7.com/special-mail-tags/#for-submissions): `[_remote_ip]`.

**Comment by mariovalney** [comment]
More details: https://wordpress.org/support/topic/how-to-use-special-mail-tags-to-get-ip-date-and-other-data/
