### ISSUE TITLE
Issue "Can't use function return value in write context" after update

### ISSUE THREAD

**Issue by tradge** [mariovalney/cf7-to-zapier#2]
Fatal error: Can't use function return value in write context in /home/slumberparty/public_html/wp-content/plugins/cf7-to-zapier/modules/zapier/class-module-zapier.php on line 60

crashes website if I enable the plugin after update. any way to get old version?

**Comment by mariovalney** [comment]
Hi! How are you?

Seems it happens in prior to PHP 5.5, because `empty()` only supports variables.

Fixed in e446d6870260324635f60b4e1cc2c22eeafc36da 

Please update to 1.1.1 and thanks for reporting.
