### ISSUE TITLE
Zapier We couldn’t find a request

### ISSUE THREAD

**Issue by Zatoweegie** [mariovalney/cf7-to-zapier#7]
Hey. First time using this plugin and Zapier does not see the hook within the form? I keep getting a "We couldn’t find a request". I have submitted forms etc but still no joy.

Screenshot attached of the set up but not sure why Zapier will not see it.

Any help would be appreciated.

![Screenshot 2020-09-23 at 13 52 36](https://user-images.githubusercontent.com/71769790/94014983-30002080-fda4-11ea-9d75-8ad9e4f2ade9.png)

**Comment by mariovalney** [comment]
Hi.
It would be a server problem or maybe config (on Zapier).

Let's check the second case first:

1 - Visit [webhook.site](https://webhook.site)
2 - Try the given webhook on your form

Any request received?

**Comment by Zatoweegie** [comment]
Thanks for getting back. I displayed the attached. Seemed to work.

![Screenshot 2020-09-23 at 17 29 11](https://user-images.githubusercontent.com/71769790/94041574-5339c880-fdc2-11ea-9a3f-a67b1fbbaba9.png)

**Comment by mariovalney** [comment]
Actually no. It seems to be a GET (did you open the URL in browser maybe?).
There should be a POST after submitting the form.

**Comment by Zatoweegie** [comment]
Believe t or not when I put back in the Zapier hook it found it!

**Comment by Zatoweegie** [comment]
Might have been a delay or something

**Comment by mariovalney** [comment]
It happens... hahaha

Nice to hear it's working now. :)
I'll close the issue, ok?

**Comment by Zatoweegie** [comment]
seems to be working now. Thanks! :D
