### ISSUE TITLE
Integrate directly to specific API

### ISSUE THREAD

**Issue by cfontes** [mariovalney/cf7-to-zapier#8]
Boa tarde!

First thanks for this, it is very useful.

I am trying to have my form to send the user data directly to Trello to avoid running into Zapier Limits ( which is super low now, 100 tasks per month)

In order to do that, I need my form data to match Trello's API in this case.

I am not sure how to achieve that, the main issue is that I need to do some data transformation an example is

The data is current this

```
{
    "name": "??????",
    "contact-name": "??????",
    "contact-email": "??????",
    "contact-phone": "??????",
    "income": "??????",
}
```

And thru the magic of PHP it needs to become x-www-form/urlencoded with this

?name=contact-name?desc=***all other fields plus some added fixed strings****

Is there a way to achieve that?

P.S: Muito legal ver código de brasileiros brilhando por ai, valeu!

**Comment by mariovalney** [comment]
Hey! How are you?

_Como é uma issue mais de suporte, vou manter em portuga mesmo haha_

Olha... dá pra alterar a requisição sim.
Basta usar os filtros. 

Por exemplo, para [alterar os headers](https://wordpress.org/support/topic/additional-headers-4/#post-12118058):

```
add_filter( 'ctz_post_request_args', 'cfontes_ctz_post_request_args' );
function cfontes_ctz_post_request_args( $args ) {
    $args['headers']['Content-Type'] = 'application/x-www-form-urlencoded';

    return $args;
}
```

O filtro é [ctz_post_request_args](https://github.com/Vizir/cf7-to-zapier/blob/master/modules/zapier/class-module-zapier.php#L92). Mas eu percebi agora que não passo a URL pra ele, então não tem como ter certeza que o envio é o que você quer. Talvez seja necessário fazer um parse no `$args['body']` para decidir se vai adicionar ou não o header.

E para alterar o formato dos dados é o filtro [ctz_get_data_from_contact_form](https://github.com/Vizir/cf7-to-zapier/blob/master/modules/cf7/class-module-cf7.php#L357).

**Uma outra abordagem** é usar a action [ctz_trigger_webhook](https://github.com/Vizir/cf7-to-zapier/blob/master/modules/cf7/class-module-cf7.php#L226) e criar a requisição você mesmo.

O problema é que não teria como evitar a outra requisição e daria problema, então vai ter que ser o primeiro.

Abraços

**Comment by mariovalney** [comment]
Se tiver disposto, poderíamos abrir uma issue pra facilitar isso ae.. kkk

No mínimo adicionar a URL no filtro _ctz_post_request_args_ ou então um filtro para evitar a requisição padrão e permitir adicionar requisições no _ctz_trigger_webhook_

**Comment by cfontes** [comment]
Opa, valeu pela resposta.

Meu forte é Java, no PHP eu sou amador :D, mas posso tentar implementar.

Eu preciso dar uma estudada no código e estudar um pouco mais de PHP.

Mas como não tem nada que faz o que eu quero sem passar por integradores tipo o Zapier, acho que vale uma tentativa.

 ctz_trigger_webhook me parece mais legal, porque o que eu quero mesmo e utilizar os dados do form para montar o request para a API e aproveitar o server para filtrar eles formatar e categorizar os cards com labels e tudo mais.

**Comment by eagleDiego** [comment]
Hi guys, I'm not sure I get all of the Portuguese right, but sounds like you're talking about sending custom Headers here.

I know I can easily solve this with Zapier, but I'm a bit of a purist. Would it be possible to add an option to pass a list of custom headers?

My use case is to subscribe a user to a newsletter list on MailBlast.io and to authenticate the request I need to send credentials as a Header.

Sorry my level of PHP or knowledge of WP is nowhere near what's required to send a PR :(

Great job on this great integration! 👍 🇧🇷

**Comment by mariovalney** [comment]
Hi @eagleDiego :) 

[This support topic](https://wordpress.org/support/topic/additional-headers-4/#post-12111185) may be what you need.

I have in my roadmap to add a feature to users add headers to every webhook, but I'm not sure when I'll be able to delivery it.

```php
add_filter( 'ctz_post_request_args', 'eaglediego_ctz_post_request_args' );
function eaglediego_ctz_post_request_args( $args ) {
    $args['headers']['your-header-1'] = 'your-value-here';
    $args['headers']['your-header-2'] = 'your-value-here';
    $args['headers']['your-header-3'] = 'your-value-here';

    return $args;
}
```

If you are not OK creating custom plugins or adding code to your theme, let me know so I can help you.
_I would like to ask you to [create a new topic in support forum](https://wordpress.org/support/plugin/cf7-to-zapier/#new-topic-0). This way we'll be able to help more people._

**Comment by mariovalney** [comment]
Closing because we now support custom headers.
