### ISSUE TITLE
Make timeout of webhook configurable

### ISSUE THREAD

**Issue by koenvo** [mariovalney/cf7-to-zapier#9]
It would be great to be able to specify a timeout per webhook. Currently it doesn't seem to be supported and I had to change the code at https://github.com/Vizir/cf7-to-zapier/blob/55701e9d0e93427fdc7d0db813075c6a154dd7c0/modules/zapier/class-module-zapier.php#L66-L72

I would be happy to implement it and create a Pull Request for this if appreciated. In that case I might need some pointers on where to make changes.

**Comment by mariovalney** [comment]
Hi. How are you?

The plugin provides a filter.
You can use "ctz_post_request_args" to change the request args.

```php
add_filter( 'ctz_post_request_args', 'koenvo_ctz_post_request_args' );
function koenvo_ctz_post_request_args( $args ) {
    $args['timeout'] = 9999;
    return $args;
}
```

Thanks for offering help but I guess less options is better as [WordPress states](https://make.wordpress.org/core/handbook/about/philosophies/#decisions-not-options).
